markdown: rdiscount
highlighter: pygments
permalink: /:year/:month/:day/:title.html
name: "cojing"
markdown: rdiscount

author: "cojing"
atom-baseurl: "http://cojing.com"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html

